### PR TITLE
Minor Performance Enhancements and UI Updates/Changes

### PR DESCRIPTION
**Pull request by JesseChrestler**
Map no longer needs be rebuilt every time we get new data. Markers are managed separately from the map.
Added a loading indicator to notify the user when we are attempting to get data from pgo server.
Added a refresh rate input so you can adjust the refresh rate.

### CODE REVIEW

**Comment by JPHamlett1993** [comment]
Love this! Built on my personal branch!

**Comment by JesseChrestler** [comment]
Made quite a few more updates. Should be stable now.

**Comment by orienw** [comment]
really cool additions! one UX feedback: maybe when you select map center mode, and move around on the map past a certain distance, trigger a refresh rather than wait for the preconfigured X (30) seconds?

**Comment by JesseChrestler** [comment]
Yeah, I was thinking the same. Or give you a manual search button so you
search anytime you want. This will also allow you to search  more than
once.

**Comment by JesseChrestler** [comment]
Fixed

**Comment by emeth-** [comment]
@JesseChrestler These are awesome improvements! Well done!

I'm porting them (and some pieces from other pull requests) to the master branch. Going to try to make the load requests asyncronous as well to get around Heroku's 30 second time limits.

**Pull request merged**
