### PR TITLE
Better scan cells

### PR DESCRIPTION
**Pull request by ngunia**

### CODE REVIEW

**Comment by emeth-** [comment]
I like this a lot. In my testing, updates lasted from about 20-35 seconds, bringing it right up on the edge of Heroku's 30 second timeout. 

I'm running this version locally on my machine for the bigger picture view, and using the smaller version for my mobile app that returns faster (but scans a smaller space). Thanks man!

**Comment by ClintOxx** [comment]
Decided to try this after seeing your pull request in the base branch and man the scanning works pretty well, good job

**Comment by OSwoboda** [comment]
I've tried it aswell, but doesn't get any pokemon_data:
`pokemon_data []`

Edit: To clarify, I'm getting data with the master: https://github.com/emeth-/pokelocater/issues/14#issuecomment-233619868

**Comment by ngunia** [comment]
I was having some issues after I made this PR, but I am not sure if it was because of the server load in the afternoon yesterday.  It definitely takes a bit longer than the smaller area scan.  I will go back and decrease the scan distance, and see how it goes.  I think it might be a good idea to make the radius a configurable value so it can be cut back when the servers are overloaded.  I can't do any work on this today, but I'll tweak it a bit tomorrow.

**Comment by adrianocr** [comment]
@ngunia a suggestion on my part would be to make the scan radius a url parameter. Most of these maps I've seen do the scanning in "steps". So http://yourdomain.com/s=5 would scan 5 steps. The project uses django so routing that shouldn't be difficult I think (although I'm not too familiar with django)

**Comment by ClintOxx** [comment]
I had problems but it was the server instability causing them for me yesterday. After that cleared up the tracker worked pretty well just takes longer like you said

**Comment by ngunia** [comment]
@adrianocr yeah I was thinking of something like that, I need to do some research on how far a "step" is though.

**Comment by equals215** [comment]
@ngunia can you help me adding more cells to the pokemon scanning range ?

**Pull request closed without merging**
